### ISSUE TITLE
Лаба 2

### ISSUE THREAD

**Issue by irinamatveeva** [aaalenushkaa/BDssau#1]
Хорошим тоном считается запись всех sql команд заглавными буквами, а все остальное малыми. Например, в задании 1 должно быть SELECT ... FROM.... 
Все файлы должны содержать комментарии.
Задание 5 - в выборку попали и бесплатные объекты.
Задание 7 - рекомендуется OR использовать IN(....)
Задание 8 и далее - пока не сделаны

**Comment by lasbio** [comment]
Нет комментариев
2.3; 2.4; 2.5 - по заданию надо отбирать только объекты.
2.7 ошибка, надо использовать IN 
2.8 - пуст
2.9 - выборка "за" сентябрь 2012, в задании "с" сентября 2012.
2.10 - пусто
2.11 - не правильно
2.13 - пусто.
2.14  - пусто.

**Comment by lasbio** [comment]
1. Не выполнен пункт 1 задания ("сохранить в корне проекта") и пункт 5 ("Внесите файл создания базы данных в gitignore")
2. задание 10 - в задании нет требования сортировки, т.е. надо отобрать первых 10 членов клуба. А у вас отобраны первые 10 по алфавиту.

**Comment by aaalenushkaa** [comment]
Здравствуйте, исправила 2 лабораторную и загрузила 3
