### ISSUE TITLE
Лаб 3

### ISSUE THREAD

**Issue by lasbio** [aaalenushkaa/BDssau#3]
2 - не верно. Зачем IF в отборе? По условиям задачи надо отобрать любые теннисные корты, т.е. в условиях задачи нет facid IN (0,1). LIKE с полями типа timestamp не применяют.
4 - не верно. У Вас в списке не будет членов без рекомендации.
5 - не верно. В задаче нет условий "только члены" и facid IN (0,1).
7 - не верно.

**Comment by aaalenushkaa** [comment]
Исправила ошибки в 3 лабораторной

**Comment by lasbio** [comment]
7 - не точно. Ваш скрипт возвращает 29 членов, а в базе их 30.

**Comment by aaalenushkaa** [comment]
Добрый день, 7 задание из 3 лабы исправила
